name: Python CI

on: [push, pull_request]

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run dummy Python test
        run: |
          echo "Running Python test..."
          python -c "print('✅ Python CI is working!')"
