name: Dummy CI

on: [push, pull_request]

jobs:
  dummy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run fake test
        run: |
          echo "✅ CI is working without installing anything!"
          exit 0
